### PR TITLE
CC - Fix null pointer exception. Handle the case when the column value i...

### PR DESCRIPTION
**Pull request by charleswhchan**
CC - Fix null pointer exception. Handle the case when the column value is NULL, for column type TEXT and BLOB.

For more information, see:
http://www.sqlite.org/c3ref/column_blob.html

### CODE REVIEW

**Comment by charleswhchan** [comment]
@fnoyanisi: Could you please review this PR?

**Comment by fnoyanisi** [comment]
Thank you! I will look into that and update the repository accodringly, sorry for the late reply.

**Comment by charleswhchan** [comment]
@fnoyanisi: No worries! Thanks for building this great extension!

**Comment by charleswhchan** [comment]
Oh I see you have committed the fix! I will close the PR.

**Comment by fnoyanisi** [comment]
All done! Thanks

**Pull request closed without merging**
